on:
  push:
    branches:
      - readme-test

name: Generate readme

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Generate readme
        run: go run ./tools/readme-docs/main.go

      - name: Commit changes
        continue-on-error: true
        run: |
          git checkout readme-test
          git add README.md
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          COAUTHOR=`git log -1 --pretty=format:'\n\nCo-authored-by: %an <%ae>'`
          git commit -m "docs: updated readme$COAUTHOR"

      - name: Push changes
        if: ${{ success() }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push
